import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

export function writeTypingContentManifest(catalog: { id: string; lessons: { id: string }[] }[], projectRoot = process.cwd()) {
  const imports = catalog.flatMap((level) => level.lessons.map((lesson) => {
    const key = JSON.stringify(`${level.id}:${lesson.id}`);
    const source = JSON.stringify(`../content/typing-practice/lessons/${level.id}/${lesson.id}.json`);
    return `  ${key}: () => import(${source}).then((module) => module.default as TypingLessonPayload),`;
  }));
  writeFileSync(resolve(projectRoot, "lib/typing-content-loaders.ts"), [
    '// Generated by content:typing:import. Full lesson data is server-only.',
    'import "server-only";',
    'import type { TypingLessonPayload } from "./typing-practice.ts";',
    '',
    'export const typingContentLoaders: Record<string, () => Promise<TypingLessonPayload>> = {',
    ...imports,
    '};',
    '',
  ].join("\n"), "utf8");
}
